#!/bin/bash

#Written by Valec 2006. Steal and share.
#Get postfix queue lengths

#extend mailq /opt/observer/scripts/getmailq.sh

QUEUES="incoming active deferred hold"

for i in $QUEUES; do
        COUNT=$(sudo /usr/sbin/qshape $i | grep TOTAL | awk '{print $2}')
        printf "$COUNT\n"
done
